name: Build and deploy Node.js app to Azure Web App - intern-ash-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'   # ✅ Match Azure runtime

      - name: Install dependencies
        run: |
          npm ci                # ✅ Faster & consistent install (use ci instead of install)
      
      - name: Build (if applicable)
        run: npm run build --if-present

      - name: Archive production-ready files
        run: |
          rm -rf node_modules   # ✅ Don’t send local node_modules
          zip -r app.zip . -x "*.git*"
      
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip package
        run: unzip app.zip -d .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'intern-ash-prod'
          slot-name: 'staging'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DCB8F38C8FE54346BB70761F9153CC12 }}
          package: .
